### ISSUE TITLE
Error in solve.default(XX.wait - XX) :  Lapack routine dgesv: system is exactly singular: U[2,2] = 0

### ISSUE THREAD

**Issue by CelieDs** [junyzhou10/clusterMLD#1]
Hi there!

Thank you for the great tool! I have been trying to use the LongDataCluster function on my own data but I get the following error : 

`Error in solve.default(XX.wait - XX) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0`

This is the code I used:
`test1<- LongDataCluster(x = test1$timepoint,
                        Y = as.matrix(test1 %>% select(-id, -timepoint)),
                        id = test1$id)`

Here is my test dataset: 

id,timepoint,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10
1,0,23,17,27,17,9,19,29,38,22,117
1,1,11,18,26,19,17,17,32,36,22,124
1,2,22,17,30,17,12,25,30,39,24,130
2,0,24,23,27,16,22,21,26,19,18,106
2,1,14,22,31,18,20,21,31,23,19,114
2,2,27,21,31,20,23,22,25,20,17,107
3,0,15,20,22,18,21,23,18,30,22,114
3,1,17,21,28,18,26,27,22,29,27,131
3,2,19,21,30,20,30,28,24,27,21,130
4,0,26,28,40,19,34,20,34,23,15,126
4,1,26,28,40,19,33,25,27,24,14,123
4,2,27,28,40,17,33,23,25,21,18,120
5,0,28,21,30,20,17,21,14,25,23,100
5,1,31,19,26,19,22,29,15,10,22,98
5,2,33,13,23,22,22,18,15,17,17,89

**R version 4.4.2 (2024-10-31 ucrt)**

Thanks you for your help, 

Best regards, 

Célie

**Comment by junyzhou10** [comment]
Hi Celie,

Thank you for your interests. It seems the error is related to getting the inverse of the matrix. 

Please 
1) try to make sure that there is no missing data in your dataset.
2) I would try to reduce the y to let’s say, 2 or 3, and rerun the code, see if the error is still there.

Let me know if there is anything you find,

Best,
Junyi

**Comment by CelieDs** [comment]
Hi Junyi,

Thank you for getting back to me and providing suggestions. I have checked, and there is no missing data in my dataset. Additionally, I tried reducing the dimensionality of y by selecting different combinations of columns, but unfortunately, the error persists for all of them.

Let me know if there's any other information I can provide to help troubleshoot this issue.

Best regards,

Celie

**Comment by CelieDs** [comment]
I tested the function on a dummy dataset and noticed that the error occurs when the number of timepoints is less than 7.

For example, this setup works without issues:
`example_data <- data.frame(timepoint = rep(1:7, each = 10), var1 = rnorm(70), var2 = rnorm(70), id = rep(1:7, times = 10))`
`LongDataCluster(x = example_data$timepoint,Y = example_data %>% select(-id, -timepoint), id = example_data$id`

But for this I get `task 1 failed - "Lapack routine dgesv: system is exactly singular: U[2,2] = 0`: 

`example_data <- data.frame(timepoint = rep(1:3, each = 10), var1 = rnorm(30), var2 = rnorm(30), id = rep(1:3, times = 10))`
`LongDataCluster(x = example_data$timepoint,Y = example_data %>% select(-id, -timepoint), id = example_data$id`

Could the limited number of timepoints (e.g., 3 in my initial dataset) be causing this issue?

Bests, 

Celie

**Comment by junyzhou10** [comment]
Hello Celie,

Thank you for the prompt and nice code checking.

I guess I know the reason now. It is because we use spline basis to model the trajectories, and the default function adopted is splines::bs(). The default degree is 3 for cubic splines, which might be too much for your dataset. You can try to use … in the main function LongDataCluster() to change the bs() settings, e.g., by directly adding something like LongDataCluster(<other arguments>, degree = 2). Please play with it and let me know whether it helps. 

Thank you!
Junyi

**Comment by CelieDs** [comment]
Hello Junyi,

Thank you for your response.
I experimented with changing the degree value, but unfortunately, it still doesn’t work. Interestingly, when I set the degree to 4, the error changes to:
`Error in solve.default(XX.wait - XX): system is computationally singular: reciprocal condition number = 1.27553e-20.`

Best regards,
Celie

**Comment by junyzhou10** [comment]
Hi Celie,

Sorry for the late response. I am a little bit swamped this week. 

The problem is still the lack of enough degree of freedom for fitting b-splines here. So I suggest to change the basis to natural splines by using the following arguments

LongDataCluster(x = test1$timepoint, 
                       Y = as.matrix(test1 %>% select(-id, -timepoint)), 
                       id = test1$id, 
                       functional = "ns", df = 3)

In general, given such limited record per person, it is not allowed to use large df here. If your example data is really well-aligned (i.e., each observation for every subject happens at the same timepoint), some other packages can be more suitable. 

Best,
Junyi

**Comment by CelieDs** [comment]
Hi Junyi,

Thank you for your response.

I tried your suggestion of using natural splines with df = 3, and it worked very well! I really appreciate the time you took to help me out.

Thank you again for your help :)

Best,

Celie

**Comment by junyzhou10** [comment]
No problem. Very happy to. And appreciate your findings here. Thank you.

Junyi
